    - name: Deploy to Azure Container Apps
      run: |
        IMAGE_NAME=${{ secrets.AZURE_ACR_NAME }}.azurecr.io/genai-chatbot:${{ github.sha }}

        echo "Deploying $IMAGE_NAME to Container App: ${{ secrets.AZURE_CONTAINERAPP_NAME }}"

        # Create Container App if it doesn't exist
        az containerapp show \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || \
        az containerapp create \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image $IMAGE_NAME \
          --environment praven18gebai \
          --cpu 0.5 --memory 1.0Gi \
          --min-replicas 1 --max-replicas 2 \
          --set-env-vars AZURE_OPENAI_KEY=${{ secrets.AZURE_OPENAI_KEY }} AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}

        # Attach ACR registry (one-time setup)
        az containerapp registry set \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --server ${{ secrets.AZURE_ACR_NAME }}.azurecr.io \
          --username ${{ secrets.ACR_USERNAME }} \
          --password ${{ secrets.ACR_PASSWORD }}

        # Update container app with new image + env vars
        az containerapp update \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image $IMAGE_NAME \
          --set-env-vars AZURE_OPENAI_KEY=${{ secrets.AZURE_OPENAI_KEY }} AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}
