name: Build and Deploy to Azure

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Azure
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

    - name: Build and Push Docker Image
      run: |
        IMAGE_NAME=${{ secrets.AZURE_ACR_NAME }}.azurecr.io/genai-chatbot:${{ github.sha }}
        az acr build --registry ${{ secrets.AZURE_ACR_NAME }} --image $IMAGE_NAME .

    - name: Deploy to Azure Container Apps
      run: |
        IMAGE_NAME=${{ secrets.AZURE_ACR_NAME }}.azurecr.io/genai-chatbot:${{ github.sha }}

        echo "Container App Name: ${{ secrets.AZURE_CONTAINERAPP_NAME }}"
        echo "Resource Group: ${{ secrets.AZURE_RESOURCE_GROUP }}"
        echo "Image Name: $IMAGE_NAME"

        # Create Container App if it doesn't exist
        az containerapp show \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} || \
        az containerapp create \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image $IMAGE_NAME \
          --environment praven18gebai \
          --cpu 0.5 --memory 1.0Gi \
          --min-replicas 1 --max-replicas 2 \
          --set-env-vars AZURE_OPENAI_KEY=${{ secrets.AZURE_OPENAI_KEY }} AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}

        # Update container app with new image + env vars
        az containerapp update \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --image $IMAGE_NAME \
          --set-env-vars AZURE_OPENAI_KEY=${{ secrets.AZURE_OPENAI_KEY }} AZURE_OPENAI_ENDPOINT=${{ secrets.AZURE_OPENAI_ENDPOINT }}

    - name: Verify Deployment
      run: |
        echo "Fetching Container App URL..."
        APP_URL=$(az containerapp show \
          --name ${{ secrets.AZURE_CONTAINERAPP_NAME }} \
          --resource-group ${{ secrets.AZURE_RESOURCE_GROUP }} \
          --query "properties.configuration.ingress.fqdn" -o tsv)

        echo "App deployed at: https://$APP_URL"
        echo "Making test request..."
        curl -v "https://$APP_URL"
